import localFont from "next/font/local";
import "./globals.css";
import AdminLayout from "./components/adminLayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AdminLayout>
          {children}
        </AdminLayout>
        <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
                <h1>ini footer</h1>
          </footer>
      </body>
    </html>
  );
}
